### ISSUE TITLE
home assistant integration

### ISSUE THREAD

**Issue by gunnm80** [freaktechnik/maxsmart2-adapter#1]
Hello
Perhaps you can help me further? I am looking for a suitable home assistant integration for this Max Hauri Clip-Clap SmartPlug 2.0 type SOW017. Unfortunately, the MaxSmart (Revogi) integration does not work. And the app is no longer available...
Thank you very much.
Greetings

**Comment by freaktechnik** [comment]
I can't, sorry. I don't use home assistant myself. https://github.com/freaktechnik/mh-maxsmart2 is the actual protocol implementation, so that's what'd need to be ported to python for homeassistant as far as I understand.
